[svr_volc]
;提交 ASR 任务
volc_asr_submit                      = 'api/v3/auc/bigmodel/submit'
;查询 ASR 结果
volc_asr_query                       = 'api/v3/auc/bigmodel/query'
[svr_volc_text]
;获取文本标题&摘要
volc_chat_completions                = 'api/v3/chat/completions'
